apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: legendary-giggle
  description: "This project details a robust, idempotent, and resilient Python script for synchronizing VoIP.ms call recordings to a local directory, designed for scheduled execution and containerized deployment."
  annotations:
    github.com/project-slug: sparksis/legendary-giggle
spec:
  type: service
  lifecycle: experimental
  owner: sparksis